#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'https://tuantmdev.github.io/'

#change it according to your repository name
# disabling since we are using a custom domain
# baseurl: '/online-cv' 

description: Hi, I'm Tuan! I'm a driven professional with a passion for Software Development. With experience in team management, project management, and iOS development, I bring a unique blend of technical expertise and leadership skills to the table. My portfolio showcases my achievements and skills in Software Development. I'm always striving to learn and grow, and I'm eager to bring my passion and skills to a new challenge. Thanks for visiting my online CV portfolio!
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: berry # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: G-NL53HRKCYK

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
